server:
  port: 9090
  servlet:
    context-path: /product-service
spring:
  application:
    name: Product Microservice
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shopping